### ISSUE TITLE
Optimization of config.php.sample

### ISSUE THREAD

**Issue by stemind** [u5cms/u5cms#41]
Line 27 shall be $usesmtp='yes';
Lines 42 to 46 shall be removed;

**Comment by mrolli** [comment]
As presumed these changes are already addressed, see [this
commit](https://github.com/u5cms/u5cms/pull/38/commits/a4c87d6c8d210a578e5df10f389444849166d53e).
The current version of
https://github.com/u5cms/u5cms/blob/main/config.php.sample does not have these
leftovers anymore. Where have you seen these? Maybe in the big flower context?
These instances are probably not yet at the latest commit.

Regarding your `$usesmtp` request: This was already requested to be `no` in
issue #37 and fixed in PR #39. Shall I leave it to `no` or do you prefer
reverting #39?

**Comment by mrolli** [comment]
Hey Stefan, do you prefer $usesmtp to be `yes` or `no` in config.php.sample?

**Comment by mrolli** [comment]
Default == no!

**Comment by mrolli** [comment]
Already correctly set to no
